spring.application.name=ms_calls
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require&preferQueryMode=simple
spring.datasource.username=postgres.qshwkpcwpcvppnlgworm
spring.datasource.password=betungas12:V
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8082